import os
import sys
import json
import glob
import streamlit as st

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agents.feedback_agent.feedback_agent import FeedbackAgent
from ui_components import inject_css, render_section_label, render_badge, render_callout

st.set_page_config(
    page_title="Model Insights | CropGuardian AI",
    page_icon="📊",
    layout="wide",
)
inject_css()


# ─── Cached Agent ─────────────────────────────────────────────────────────────
@st.cache_resource
def get_feedback_agent():
    return FeedbackAgent()

feedback_agent = get_feedback_agent()


# ─── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🌿 CropGuardian AI")
    st.divider()
    st.markdown("**📊 Model Insights**")
    st.caption(
        "Evaluation metrics are generated by running `src/evaluation/metrics.py` "
        "against a test dataset and saving reports to the `reports/` directory."
    )
    st.divider()
    st.markdown("**🔄 Feedback Loop**")
    st.caption(
        "User corrections from the Feedback page are logged here in real time. "
        "Export them via the Feedback page to build a retraining dataset."
    )


# ─── Page Header ─────────────────────────────────────────────────────────────
st.markdown("## 📊 Model Insights")
st.caption("Evaluation metrics, model health reports, and live feedback statistics.")
st.divider()


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION A: EVALUATION PIPELINE REPORTS
# ═══════════════════════════════════════════════════════════════════════════════
render_section_label("Evaluation Pipeline Reports")

# Resolve reports directory (support fallback for testing)
reports_dir = "reports"
if not os.path.exists(reports_dir) and os.path.exists("reports_dummy"):
    reports_dir = "reports_dummy"

if not os.path.exists(reports_dir):
    with st.container(border=True):
        st.markdown("**No reports directory found**")
        st.caption(
            "Run the evaluation pipeline to generate reports. "
            "Reports are expected in the `reports/` directory with the naming pattern:\n\n"
            "- `<prefix>_metrics.json`\n"
            "- `<prefix>_confusion_matrix.png`\n"
            "- `<prefix>_model_health_report.md`"
        )
    st.divider()
else:
    metrics_files = glob.glob(os.path.join(reports_dir, "*_metrics.json"))

    if not metrics_files:
        st.info("No evaluation metrics found in the reports directory.")
    else:
        prefixes = [os.path.basename(f).replace("_metrics.json", "") for f in metrics_files]
        selected_prefix = st.selectbox(
            "Select Evaluation Dataset",
            prefixes,
            label_visibility="visible",
        )

        # ── Key Metrics ──────────────────────────────────────────────────────
        metrics_path = os.path.join(reports_dir, f"{selected_prefix}_metrics.json")
        try:
            with open(metrics_path, "r") as f:
                metrics = json.load(f)

            render_section_label("Performance Metrics")
            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Overall Accuracy", f"{metrics.get('accuracy', 0) * 100:.2f}%")
            m2.metric("Weighted F1 Score", f"{metrics.get('f1_score', 0):.4f}")
            m3.metric("Weighted Precision", f"{metrics.get('precision', 0):.4f}")
            m4.metric("Weighted Recall", f"{metrics.get('recall', 0):.4f}")

        except Exception as e:
            st.error(f"Error loading metrics file: {e}")

        st.divider()

        # ── Confusion Matrix ──────────────────────────────────────────────────
        cm_path = os.path.join(reports_dir, f"{selected_prefix}_confusion_matrix.png")
        if os.path.exists(cm_path):
            render_section_label("Confusion Matrix")
            with st.container(border=True):
                st.image(cm_path, use_container_width=True)
            st.divider()

        # ── Model Health Report ───────────────────────────────────────────────
        health_path = os.path.join(reports_dir, f"{selected_prefix}_model_health_report.md")
        if os.path.exists(health_path):
            render_section_label("Model Health Report")
            with st.container(border=True):
                try:
                    with open(health_path, "r") as f:
                        st.markdown(f.read())
                except Exception as e:
                    st.error(f"Error loading health report: {e}")
            st.divider()


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION B: LIVE FEEDBACK STATISTICS
# ═══════════════════════════════════════════════════════════════════════════════
render_section_label("Feedback Intelligence")
st.markdown("")

stats = feedback_agent.get_feedback_stats()
total_feedback   = stats["total_feedback"]
confused_class   = stats["most_confused_class"] or "N/A"
avg_wrong_conf   = stats["average_wrong_confidence"]

f1, f2, f3 = st.columns(3)

with f1:
    with st.container(border=True):
        st.metric("Total Corrections Logged", total_feedback)

with f2:
    with st.container(border=True):
        display = confused_class if len(str(confused_class)) < 30 else str(confused_class)[:27] + "…"
        st.metric("Most Confused Class", display)
        if confused_class != "N/A":
            st.caption("Class most frequently corrected by users.")

with f3:
    with st.container(border=True):
        st.metric("Avg Confidence at Misprediction", f"{avg_wrong_conf}%")
        if avg_wrong_conf > 0:
            st.progress(avg_wrong_conf / 100)

st.markdown("")
if total_feedback > 0:
    render_callout(
        f"Feedback system is active. {total_feedback} correction(s) have been logged "
        "and are available for model retraining via the Export function.",
        kind="success",
    )
else:
    st.info(
        "No user corrections have been submitted yet. "
        "Incorrect predictions can be reported on the Disease Detection page "
        "or the Feedback Submission page."
    )
